In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../data.csv')

In [4]:
df.drop("Unnamed: 32", axis=1, inplace=True)

In [5]:
df.drop('id',axis=1, inplace=True)

In [6]:
df['diagnosis']=df['diagnosis'].map({'B':0,'M':1})

In [7]:
df = df.sample(frac=1)

In [8]:
cl1 = df[:284]
cl2 = df[284:]

In [9]:
cl1.to_csv('./cl1.csv', encoding='utf-8')
cl2.to_csv('./cl2.csv', encoding='utf-8')

In [10]:
from sklearn.model_selection import train_test_split

# splitting data
X_train, X_test, y_train, y_test = train_test_split(
                df.drop('diagnosis', axis=1),
                df['diagnosis'],
                test_size=0.2,
                random_state=42)

print("Shape of training set:", X_train.shape)
print("Shape of test set:", X_test.shape)

Shape of training set: (455, 30)
Shape of test set: (114, 30)


In [11]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.fit_transform(X_test)

In [12]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)
predictions1 = logreg.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix, classification_report

print("Confusion Matrix: \n", confusion_matrix(y_test, predictions1))
print('\n')
print(classification_report(y_test, predictions1))

Confusion Matrix: 
 [[78  1]
 [ 2 33]]


              precision    recall  f1-score   support

           0       0.97      0.99      0.98        79
           1       0.97      0.94      0.96        35

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



In [14]:
predictions1 = logreg.predict(X_train)
print(classification_report(y_train, predictions1))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       278
           1       0.99      0.98      0.99       177

    accuracy                           0.99       455
   macro avg       0.99      0.99      0.99       455
weighted avg       0.99      0.99      0.99       455



In [15]:
 
# [[64  4]
# [ 1 45]]

In [72]:
from xgboost import XGBClassifier 

xgb = XGBClassifier(objective = 'binary:logistic', learning_rate = 0.5, max_depth = 5, n_estimators = 180)

xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.5, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=180, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [73]:
y_pred = xgb.predict(X_test)

In [74]:
# accuracy score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_train, xgb.predict(X_train)))

xgb_acc = accuracy_score(y_test, y_pred)
print(xgb_acc)

1.0
0.956140350877193


In [75]:
xgb.get_params
print(xgb.get_params
)

<bound method XGBModel.get_params of XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.5, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=180, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)>


In [76]:
predictions1 = xgb.predict(X_test)
print("Confusion Matrix: \n", confusion_matrix(y_test, predictions1))

Confusion Matrix: 
 [[78  1]
 [ 4 31]]


In [116]:
print(metrics.classification_report(y_test, predictions1))


              precision    recall  f1-score   support

           0       0.95      0.99      0.97        79
           1       0.97      0.89      0.93        35

    accuracy                           0.96       114
   macro avg       0.96      0.94      0.95       114
weighted avg       0.96      0.96      0.96       114



In [21]:
print(xgb.get_params())

{'objective': 'binary:logistic', 'base_score': None, 'booster': None, 'callbacks': None, 'colsample_bylevel': None, 'colsample_bynode': None, 'colsample_bytree': None, 'device': None, 'early_stopping_rounds': None, 'enable_categorical': False, 'eval_metric': None, 'feature_types': None, 'gamma': None, 'grow_policy': None, 'importance_type': None, 'interaction_constraints': None, 'learning_rate': 0.5, 'max_bin': None, 'max_cat_threshold': None, 'max_cat_to_onehot': None, 'max_delta_step': None, 'max_depth': 5, 'max_leaves': None, 'min_child_weight': None, 'missing': nan, 'monotone_constraints': None, 'multi_strategy': None, 'n_estimators': 180, 'n_jobs': None, 'num_parallel_tree': None, 'random_state': None, 'reg_alpha': None, 'reg_lambda': None, 'sampling_method': None, 'scale_pos_weight': None, 'subsample': None, 'tree_method': None, 'validate_parameters': None, 'verbosity': None}


In [77]:
import xgboost as xgb
train_dmatrix = xgb.DMatrix(X_train, label=y_train)

In [78]:
valid_dmatrix = xgb.DMatrix(X_test, label=y_test)

In [79]:
import xgboost as xgb2
params = {
    "objective": "binary:logistic",
    "eta": 0.1,  # Learning rate
    "max_depth": 8,
    "eval_metric": "error",
    "nthread": 16,
    "num_parallel_tree": 1,
    "subsample": 1,
    "tree_method": "hist",
}
a = xgb2.train(params,train_dmatrix,evals=[(valid_dmatrix, "validate"), (train_dmatrix, "train")])

[0]	validate-error:0.30702	train-error:0.38901
[1]	validate-error:0.11404	train-error:0.09890
[2]	validate-error:0.05263	train-error:0.03077
[3]	validate-error:0.05263	train-error:0.01758
[4]	validate-error:0.05263	train-error:0.01319
[5]	validate-error:0.05263	train-error:0.01538
[6]	validate-error:0.06140	train-error:0.01319
[7]	validate-error:0.06140	train-error:0.01099
[8]	validate-error:0.07018	train-error:0.01099
[9]	validate-error:0.06140	train-error:0.00879


In [83]:
preds = a.predict(valid_dmatrix)

In [93]:
preds

array([0.14374082, 0.77745754, 0.77745754, 0.7627936 , 0.14374082,
       0.6731389 , 0.14374082, 0.14374082, 0.77745754, 0.17938024,
       0.14374082, 0.14374082, 0.5956062 , 0.14374082, 0.77745754,
       0.14374082, 0.77745754, 0.77745754, 0.14374082, 0.29647326,
       0.15633874, 0.77745754, 0.14374082, 0.14374082, 0.14374082,
       0.5014293 , 0.77745754, 0.37683088, 0.14374082, 0.14374082,
       0.77745754, 0.14374082, 0.14374082, 0.14374082, 0.7472261 ,
       0.14374082, 0.20582853, 0.14374082, 0.7203399 , 0.17027085,
       0.14374082, 0.19944699, 0.7627936 , 0.77745754, 0.77745754,
       0.14374082, 0.14374082, 0.14374082, 0.14374082, 0.77745754,
       0.29647326, 0.14374082, 0.14374082, 0.77745754, 0.6996335 ,
       0.2910193 , 0.77745754, 0.14374082, 0.14374082, 0.24928316,
       0.14374082, 0.14374082, 0.16844362, 0.14374082, 0.14374082,
       0.14374082, 0.77745754, 0.14374082, 0.14374082, 0.77745754,
       0.20760626, 0.20582853, 0.14374082, 0.14374082, 0.14374

In [111]:

y_pred = np.multiply(preds,100)
y_pred = y_pred.astype(int)
a = [1 if i >= 50 else 0 for i in y_pred]
print(y_pred)
print(a)


[14 77 77 76 14 67 14 14 77 17 14 14 59 14 77 14 77 77 14 29 15 77 14 14
 14 50 77 37 14 14 77 14 14 14 74 14 20 14 72 17 14 19 76 77 77 14 14 14
 14 77 29 14 14 77 69 29 77 14 14 24 14 14 16 14 14 14 77 14 14 77 20 20
 14 14 14 77 77 14 14 77 14 14 14 14 50 37 14 34 15 14 14 14 14 14 77 15
 14 19 14 14 17 14 14 14 14 77 14 77 72 14 25 14 14 14]
[0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0]


In [112]:
from sklearn import metrics 
print(metrics.classification_report(a,y_test))

              precision    recall  f1-score   support

           0       0.97      0.94      0.96        82
           1       0.86      0.94      0.90        32

    accuracy                           0.94       114
   macro avg       0.92      0.94      0.93       114
weighted avg       0.94      0.94      0.94       114



In [ ]:
from sklearn.metrics import accuracy_score
import xgboost as xgb
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
xgb_train = xgb.DMatrix(X_train, y_train, enable_categorical=True)
xgb_test = xgb.DMatrix(X_test, y_test, enable_categorical=True)

In [ ]:
n=50
params = {
}

model = xgb.train(params=params,dtrain=xgb_train)

In [ ]:
preds = a.predict(xgb_test)
preds = preds.astype(int)
accuracy= accuracy_score(y_test,preds)
print('Accuracy of the model is:', accuracy*100)

Accuracy of the model is: 62.28070175438597


In [ ]:
n_valid = 50 

train_df, valid_df = train_test_split(df, test_size=n_valid, random_state=42)
train_df.shape, valid_df.shape

((519, 31), (50, 31))

In [ ]:
from sklearn import datasets
dbunch = datasets.load_breast_cancer(as_frame=True)
df = dbunch.frame
features = dbunch.feature_names 
target_names = dbunch.target_names 
target = 'target' 


In [ ]:
import xgboost as xgb

params = {
    'tree_method': 'exact',
    'objective': 'binary:logistic',
}
num_boost_round = 50
model = xgb.train(params=params, dtrain=xgb_train, num_boost_round=num_boost_round,
                  evals=[(xgb_train, 'train'), (xgb_test, 'valid')],
                  verbose_eval=10)

[0]	train-logloss:0.43543	valid-logloss:0.46457
[10]	train-logloss:0.04345	valid-logloss:0.12834
[20]	train-logloss:0.01581	valid-logloss:0.12820
[30]	train-logloss:0.01039	valid-logloss:0.11898
[40]	train-logloss:0.00807	valid-logloss:0.12012
[49]	train-logloss:0.00715	valid-logloss:0.11911


In [ ]:
y_true = xgb_test
y_pred = model.predict(xgb_test)
y_pred = y_pred.astype(int)

In [ ]:
from sklearn import metrics 

metrics.accuracy_score(y_test, y_pred)

NameError: name 'y_test' is not defined

In [23]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn import datasets
import xgboost as xgb 

dbunch = datasets.load_breast_cancer(as_frame=True)
df = dbunch.frame
features = dbunch.feature_names 
target_names = dbunch.target_names 
target = 'target' 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [24]:
print(df[target].unique())
print(target_names)

[0 1]
['malignant' 'benign']


In [26]:
from sklearn.model_selection import train_test_split

n_valid = 50 

train_df, valid_df = train_test_split(df, test_size=n_valid, random_state=42)


In [47]:
params = {
    'tree_method': 'exact',
    'objective': 'binary:logistic',
    "eval_metric": "error",
}
num_boost_round = 50

dtrain = xgb.DMatrix(label=train_df[target], data=train_df[features])
dvalid = xgb.DMatrix(label=valid_df[target], data=valid_df[features])
model = xgb.train(params=params, dtrain=dtrain, num_boost_round=num_boost_round,
                  evals=[(dtrain, 'train'), (dvalid, 'valid')],
                  verbose_eval=10)

[0]	train-error:0.03661	valid-error:0.06000
[10]	train-error:0.00193	valid-error:0.04000
[20]	train-error:0.00000	valid-error:0.04000


[30]	train-error:0.00000	valid-error:0.04000
[40]	train-error:0.00000	valid-error:0.04000
[49]	train-error:0.00000	valid-error:0.04000


In [69]:
y_true = valid_df[target]
y_pred = model.predict(dvalid)
print(y_pred)
y_pred = np.multiply(y_pred,100)
y_pred = y_pred.astype(int)
a = [1 if i > 50 else 0 for i in y_pred]
print(y_pred)
print(a)


[9.9474996e-01 8.2008884e-04 5.7427638e-04 9.9938560e-01 9.9980158e-01
 3.6648734e-04 6.7751156e-04 1.8510033e-01 1.9934903e-01 9.9941051e-01
 9.9011552e-01 2.9164681e-03 9.9736661e-01 6.7647607e-03 9.9866307e-01
 9.7440719e-04 9.9937963e-01 9.9979180e-01 9.9909592e-01 8.5168285e-04
 9.8978269e-01 9.9860376e-01 3.6648734e-04 9.9777240e-01 9.9841523e-01
 9.9881017e-01 9.9955744e-01 9.9566603e-01 9.9951088e-01 3.6648734e-04
 9.9888796e-01 9.9895120e-01 9.3850678e-01 9.9924135e-01 9.9958390e-01
 9.9871659e-01 1.5681238e-01 9.8883635e-01 3.8794926e-04 9.9862683e-01
 9.9977821e-01 8.2779198e-04 9.9949479e-01 9.9959511e-01 9.4555068e-01
 9.8940545e-01 9.9926811e-01 9.9504483e-01 9.8442012e-01 9.9875259e-01]
[99  0  0 99 99  0  0 18 19 99 99  0 99  0 99  0 99 99 99  0 98 99  0 99
 99 99 99 99 99  0 99 99 93 99 99 99 15 98  0 99 99  0 99 99 94 98 99 99
 98 99]
[1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,

In [123]:
model.eval(dvalid,"error")

'[0]\terror-error:0.04000000000000000'

In [70]:
from sklearn import metrics 

metrics.accuracy_score(y_true, a)

0.96

In [56]:
a = [1, 2, 3] 
a = np.multiply(a,10)
print(a)

[10 20 30]


In [71]:
print(metrics.classification_report(y_true, a, target_names=target_names))

              precision    recall  f1-score   support

   malignant       0.93      0.93      0.93        15
      benign       0.97      0.97      0.97        35

    accuracy                           0.96        50
   macro avg       0.95      0.95      0.95        50
weighted avg       0.96      0.96      0.96        50

